package com.dave.util;

import java.util.HashMap;
import java.util.Map;

public class KeyCodes {
    private static final Map<Integer, String> mapping = new HashMap<>();

    public static String getKeyText(Integer key){
        return mapping.get(key);
    }

    static {
        mapping.put(0xC1,"Abnt C1");
        mapping.put(0xC2,"Abnt C2");
        mapping.put(0x6B,"Numpad +");
        mapping.put(0xF6,"Attn");
        mapping.put(0x08,"Backspace");
        mapping.put(0x03,"Break");
        mapping.put(0x0C,"Clear");
        mapping.put(0xF7,"Cr Sel");
        mapping.put(0x6E,"Numpad .");
        mapping.put(0x6F,"Numpad /");
        mapping.put(0xF9,"Er Eof");
        mapping.put(0x1B,"Esc");
        mapping.put(0x2B,"Execute");
        mapping.put(0xF8,"Ex Sel");
        mapping.put(0xE6,"IcoClr");
        mapping.put(0xE3,"IcoHlp");
        mapping.put(0x30 ,"0");
        mapping.put(0x31 ,"1");
        mapping.put(0x32 ,"2");
        mapping.put(0x33 ,"3");
        mapping.put(0x34 ,"4");
        mapping.put(0x35 ,"5");
        mapping.put(0x36 ,"6");
        mapping.put(0x37 ,"7");
        mapping.put(0x38 ,"8");
        mapping.put(0x39 ,"9");
        mapping.put(0x41 ,"A");
        mapping.put(0x42 ,"B");
        mapping.put(0x43 ,"C");
        mapping.put(0x44 ,"D");
        mapping.put(0x45 ,"E");
        mapping.put(0x46 ,"F");
        mapping.put(0x47 ,"G");
        mapping.put(0x48 ,"H");
        mapping.put(0x49 ,"I");
        mapping.put(0x4A ,"J");
        mapping.put(0x4B ,"K");
        mapping.put(0x4C ,"L");
        mapping.put(0x4D ,"M");
        mapping.put(0x4E ,"N");
        mapping.put(0x4F ,"O");
        mapping.put(0x50 ,"P");
        mapping.put(0x51 ,"Q");
        mapping.put(0x52 ,"R");
        mapping.put(0x53 ,"S");
        mapping.put(0x54 ,"T");
        mapping.put(0x55 ,"U");
        mapping.put(0x56 ,"V");
        mapping.put(0x57 ,"W");
        mapping.put(0x58 ,"X");
        mapping.put(0x59 ,"Y");
        mapping.put(0x5A ,"Z");
        mapping.put(0x6A,"Numpad *");
        mapping.put(0xFC,"NoName");
        mapping.put(0x60,"Numpad 0");
        mapping.put(0x61,"Numpad 1");
        mapping.put(0x62,"Numpad 2");
        mapping.put(0x63,"Numpad 3");
        mapping.put(0x64,"Numpad 4");
        mapping.put(0x65,"Numpad 5");
        mapping.put(0x66,"Numpad 6");
        mapping.put(0x67,"Numpad 7");
        mapping.put(0x68,"Numpad 8");
        mapping.put(0x69,"Numpad 9");
        mapping.put(0xBA,"OEM_1  ;)");
        mapping.put(0xE2,"OEM_102  <)");
        mapping.put(0xBF,"OEM_2  /)");
        mapping.put(0xC0,"OEM_3  `)");
        mapping.put(0xDB,"OEM_4  [)");
        mapping.put(0xDC,"OEM_5  \\)");
        mapping.put(0xDD,"OEM_6  ])");
        mapping.put(0xDE,"OEM_7  ')");
        mapping.put(0xDF,"OEM_8  !)");
        mapping.put(0xF0,"Oem Attn");
        mapping.put(0xF3,"Auto");
        mapping.put(0xE1,"Ax");
        mapping.put(0xF5,"Back Tab");
        mapping.put(0xFE,"OemClr");
        mapping.put(0xBC,"OEM_COMMA  ,)");
        mapping.put(0xF2,"Copy");
        mapping.put(0xEF,"Cu Sel");
        mapping.put(0xF4,"Enlw");
        mapping.put(0xF1,"Finish");
        mapping.put(0x95,"Loya");
        mapping.put(0x93,"Mashu");
        mapping.put(0x96,"Roya");
        mapping.put(0x94,"Touroku");
        mapping.put(0xEA,"Jump");
        mapping.put(0xBD,"OEM_MINUS  -)");
        mapping.put(0xEB,"OemPa1");
        mapping.put(0xEC,"OemPa2");
        mapping.put(0xED,"OemPa3");
        mapping.put(0xBE,"OEM_PERIOD  .)");
        mapping.put(0xBB,"OEM_PLUS  =)");
        mapping.put(0xE9,"Reset");
        mapping.put(0xEE,"WsCtrl");
        mapping.put(0xFD,"Pa1");
        mapping.put(0xE7,"Packet");
        mapping.put(0xFA,"Play");
        mapping.put(0xE5,"Process");
        mapping.put(0x0D,"Enter");
        mapping.put(0x29,"Select");
        mapping.put(0x6C,"Separator");
        mapping.put(0x20,"Space");
        mapping.put(0x6D,"Num -");
        mapping.put(0x09,"Tab");
        mapping.put(0xFB,"Zoom");
        mapping.put(0xFF,"no VK mapping");
        mapping.put(0x1E,"Accept");
        mapping.put(0x5D,"Context Menu");
        mapping.put(0xA6,"Browser Back");
        mapping.put(0xAB,"Browser Favorites");
        mapping.put(0xA7,"Browser Forward");
        mapping.put(0xAC,"Browser Home");
        mapping.put(0xA8,"Browser Refresh");
        mapping.put(0xAA,"Browser Search");
        mapping.put(0xA9,"Browser Stop");
        mapping.put(0x14,"Caps Lock");
        mapping.put(0x1C,"Convert");
        mapping.put(0x2E,"Delete");
        mapping.put(0x28,"Arrow Down");
        mapping.put(0x23,"End");
        mapping.put(0x70,"F1");
        mapping.put(0x79,"F10");
        mapping.put(0x7A,"F11");
        mapping.put(0x7B,"F12");
        mapping.put(0x7C,"F13");
        mapping.put(0x7D,"F14");
        mapping.put(0x7E,"F15");
        mapping.put(0x7F,"F16");
        mapping.put(0x80,"F17");
        mapping.put(0x81,"F18");
        mapping.put(0x82,"F19");
        mapping.put(0x71,"F2");
        mapping.put(0x83,"F20");
        mapping.put(0x84,"F21");
        mapping.put(0x85,"F22");
        mapping.put(0x86,"F23");
        mapping.put(0x87,"F24");
        mapping.put(0x72,"F3");
        mapping.put(0x73,"F4");
        mapping.put(0x74,"F5");
        mapping.put(0x75,"F6");
        mapping.put(0x76,"F7");
        mapping.put(0x77,"F8");
        mapping.put(0x78,"F9");
        mapping.put(0x18,"Final");
        mapping.put(0x2F,"Help");
        mapping.put(0x24,"Home");
        mapping.put(0xE4,"Ico00 *");
        mapping.put(0x2D,"Insert");
        mapping.put(0x17,"Junja");
        mapping.put(0x15,"Kana");
        mapping.put(0x19,"Kanji");
        mapping.put(0xB6,"App1");
        mapping.put(0xB7,"App2");
        mapping.put(0xB4,"Mail");
        mapping.put(0xB5,"Media");
        mapping.put(0x01,"Left Button **");
        mapping.put(0xA2,"Left Ctrl");
        mapping.put(0x25,"Arrow Left");
        mapping.put(0xA4,"Left Alt");
        mapping.put(0xA0,"Left Shift");
        mapping.put(0x5B,"Left Win");
        mapping.put(0x04,"Middle Button **");
        mapping.put(0xB0,"Next Track");
        mapping.put(0xB3,"Play / Pause");
        mapping.put(0xB1,"Previous Track");
        mapping.put(0xB2,"Stop");
        mapping.put(0x1F,"Mode Change");
        mapping.put(0x22,"Page Down");
        mapping.put(0x1D,"Non Convert");
        mapping.put(0x90,"Num Lock");
        mapping.put(0x92,"Jisho");
        mapping.put(0x13,"Pause");
        mapping.put(0x2A,"Print");
        mapping.put(0x21,"Page Up");
        mapping.put(0x02,"Right Button **");
        mapping.put(0xA3,"Right Ctrl");
        mapping.put(0x27,"Arrow Right");
        mapping.put(0xA5,"Right Alt");
        mapping.put(0xA1,"Right Shift");
        mapping.put(0x5C,"Right Win");
        mapping.put(0x91,"Scrol Lock");
        mapping.put(0x5F,"Sleep");
        mapping.put(0x2C,"Print Screen");
        mapping.put(0x26,"Arrow Up");
        mapping.put(0xAE,"Volume Down");
        mapping.put(0xAD,"Volume Mute");
        mapping.put(0xAF,"Volume Up");
        mapping.put(0x05,"X Button 1 **");
        mapping.put(0x06,"X Button 2 **");

    }
}
